feature_req/models.py
from datetime import datetime
from feature_req import db

def dump_datetime(value):
    """Deserialize datetime object into string form for JSON processing."""
    if value is None:
        return None
    return [value.strftime("%Y-%m-%d")]

class Request(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50), nullable=False)
    description = db.Column(db.String(2000), default='')
    product_area_id = db.Column(db.Integer, db.ForeignKey('product_area.id'), nullable=False)
    target_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    client_priority = db.Column(db.Integer, nullable=False)
    client_id = db.Column(db.Integer, db.ForeignKey('client.id'), nullable=False)



    def __repr__(self):
        return 'title: %s  priority %s  client_id %s' % (self.title, self.client_priority, self.client_id)


    @property
    def serialize(self):
       """Return object data in easily serializeable format"""
       return {
           'id'         : self.id,
           'target_date': dump_datetime(self.target_date),
           'priority'   :self.client_priority,
           'title'      :self.title,
           'description':self.description,
           'product_area':self.area.name,
           'client_id'  :self.client_id,
           # This is an example how to deal with One2Many relations
           'client'  : self.client.name
       }

class Client(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    #define a one-to-many relation between client and request tables
    requests = db.relationship('Request', backref='client', lazy=True)


    def __repr__(self):
        return '%s' % self.name
    @property
    def serialize(self):
       """Return object data in easily serializeable format"""
       return {
           'id'         : self.id,
           'name'       :self.name,
           'requests'   :self.requests
        }



class ProductArea(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    #define a one-to-many relation between product_area and request tables
    requests = db.relationship('Request', backref='area', lazy=True)


    def __repr__(self):
        return '%s' % self.name

feature_req/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, IntegerField, SubmitField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Length, EqualTo
from wtforms_sqlalchemy.fields import QuerySelectField, ValidationError
from feature_req.models import Client, ProductArea
from datetime import date

#get clients from DB for dynamic select field choices
def get_clients():
	return Client.query

#get product area from DB for dynamic select field choices
def get_areas():
	return ProductArea.query

#customized validator
def future_date_check(form, field):
    if field.data < date.today():
        raise ValidationError('date must be in the future')

class RequestForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    client = QuerySelectField(query_factory=get_clients,
                            get_pk=lambda c: c.id,
                            get_label=lambda c: c.name)
    clientPriority = IntegerField('Client Priority', validators=[DataRequired()])
    productArea = QuerySelectField(query_factory=get_areas,
                            get_pk=lambda pa: pa.id,
                            get_label=lambda pa: pa.name)

    description = StringField('Description')
    targetDate = DateField('DatePicker',format='%Y-%m-%d',validators=[DataRequired(), future_date_check])
    submit = SubmitField('Submit')

feature_req/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from feature_req.config import Config

db = SQLAlchemy()

def create_app(config_class=Config):

	app = Flask(__name__)
	app.config.from_object(Config)
	db.init_app(app)
	# print(app.config['SECRET_KEY'])
	from .routes import featRequests
	app.register_blueprint(featRequests)

	return app

feature_req/routes.py
from flask import render_template, redirect,url_for, jsonify, request, Blueprint
from feature_req import db
from feature_req.forms import RequestForm
from feature_req.models import Request,Client, ProductArea
from feature_req.utils import addRequest,deleteRequest, editRequest, passValuesToForm

featRequests = Blueprint('featRequests', __name__, static_folder= './feature_req/static')


#load main page
@featRequests.route("/")
@featRequests.route("/requests")
@featRequests.route("/request/clientRequests/<clientId>")
def requests(clientId=None):
    return render_template('requests.html')

#get all requests
@featRequests.route("/request/getAll", methods=['GET'])
def getRequests():
    return jsonify([r.serialize for r in Request.query.all()])

#create a new feature request
@featRequests.route('/request/add', methods=['GET','POST'])
def add():
    form = RequestForm()
    if form.validate_on_submit():
        addRequest(form)
        return redirect (url_for('featRequests.requests'))
    return render_template('requestForm.html', title='add new', form=form)

#delete a request
@featRequests.route("/request/delete/<id>", methods=['DELETE'])
def delete(id):
    if request.method == 'DELETE':
        if deleteRequest(id) =='success':
            return 'no_content',204
        return 'bad request',404

# edit a request
@featRequests.route("/request/edit/<id>", methods=['GET','POST'])
def edit(id):
    if request.method == 'GET':
        form = RequestForm()
        passValuesToForm(form,id)
        return render_template('requestForm.html', title = 'edit', form = form)

    if request.method == 'POST':
        form = RequestForm()
        if form.validate_on_submit():
            editRequest(form,id)
        return redirect(url_for('featRequests.requests')) 

# get client requests
@featRequests.route("/request/get/<clientId>", methods = ['GET'])
def getClientRequest(clientId):
      return jsonify([c.serialize for c in Client.query.filter_by(id = clientId).first().requests]);
        

feature_req/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- static CSS file -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">


    {% if title %}
        <title>Feature Requests - {{ title }}</title>
    {% else %}
        <title>Feature Requests</title>
    {% endif %}
</head>
<body>
     <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Feature Requests</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav  ml-auto">
              <a class="nav-item nav-link" href="{{ url_for('featRequests.requests') }}">Current Requests</a>
              <a class="nav-item nav-link" href="{{ url_for('featRequests.add') }}">Request a feature</a>
            </div>
          
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS, Knockout JS, and finally the app script -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
     <script type="text/javascript" src= "https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.2/knockout-min.js"></script>
    <script type="text/javascript" src= "{{ url_for('static', filename='app.js') }}"></script> 
   
</body>
</html>

feature_req/templates/requestForm.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Request a new Feature</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.client.label(class="form-control-label") }}
                    {% if form.client.errors %}
                        {{ form.client(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.client.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.client(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.clientPriority.label(class="form-control-label") }}
                    {% if form.clientPriority.errors %}
                        {{ form.clientPriority(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.clientPriority.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.clientPriority(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.productArea.label(class="form-control-label") }}
                    {% if form.productArea.errors %}
                        {{ form.productArea(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.productArea.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.productArea(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                 <div class="form-group">
                    {{ form.description.label(class="form-control-label") }}
                    {% if form.description.errors %}
                        {{ form.description(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.description.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.description(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.targetDate.label(class="form-control-label") }}
                    {% if form.targetDate.errors %}
                        {{ form.targetDate(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.targetDate.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.targetDate(class="form-control form-control-lg datepicker") }}
                    {% endif %}
                </div>
                
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

feature_req/templates/requests.html
{% extends "layout.html" %}
{% block content%}
  <h2 data-bind= "text: currentClient" class= "ml-5"></h2>
  	<ul data-bind="foreach: requests" >
          <li >
          <article class="media content-section">
            <div class="media-body">
              <div class="article-metadata">
                <span data-bind="ifnot: $parent.currentClient">
                <a class="mr-2 client" href="#" data-bind="text: client, click: $parent.changeToClientRoute"></a>
                </span>
                <small class=" text-secondary">Target Date:</small><small data-bind=" text: target_date"></small>
              </div>
              <h2><span class="article-title" href="#" data-bind=" text: title"></span></h2>
              <p class="text-secondary"> Product Area: <span class="text-dark" data-bind=" text: product_area"></span></p>
              <p class="text-secondary"> Priority: <span class="text-dark" data-bind=" text: priority"> </span></p>
              
              <p class="text-secondary" > Description: <span class=" text-darkarticle-content" data-bind=" text: description"></span></p>
            </div>
            <div class="buttons">
                <button class="btn btn-info" data-bind= "click: $parent.editReq">Edit</button>
                <button class="btn btn-dark" data-bind= "click: $parent.deleteReq">Delete</button>
            </div>
          </article>
        </li>
        </ul>
{% endblock content %}